settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: base-fiber-api
    path: ./src/cmd
    commands:
      install:
        status: true
        method: go install
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - ../../
      ignored_paths:
        - .git
        - .realize
        - vendor
